version: "3"
services:
  neo4j:
    image: docker.io/library/neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/ka1smbPooh
    ports:
      - "7474:7474"
      - "7687:7687"

  frea-interface:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URL=bolt://neo4j:7687
    env_file:
    - .env
