version: "3.8"
services:
  frea-interface:
    build: .
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URL=bolt://host.docker.internal:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=ka1smbPooh
      - VECTOR_INDEX_NAME=frea
    depends_on:
      - wait-for-neo4j
    volumes:
      - .:/app

  wait-for-neo4j:
    image: busybox
    command: /bin/sh -c "sleep 10"
